name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy WordPress to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # デプロイ用ディレクトリに移動
            cd /var/www/html

            # 必要なディレクトリを同期
            rsync -avz --delete ./wp-content/themes/ /var/www/html/wp-content/themes/
            rsync -avz --delete ./wp-content/plugins/ /var/www/html/wp-content/plugins/

            # キャッシュの削除（必要に応じて）
            sudo rm -rf /var/www/html/wp-content/cache/*

            # 権限設定
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            # Apache再起動
            sudo systemctl restart apache2
