name: Deploy WordPress to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            set -e

            # Gitリポジトリが既に存在する場合はpull、存在しない場合はクローン
            if [ -d "/var/www/html/.git" ]; then
              echo "Git repository found. Pulling latest changes..."
              cd /var/www/html
              git reset --hard
              git pull origin main
            else
              echo "No Git repository found. Resetting directory and cloning..."
              sudo rm -rf /var/www/html/*
              sudo rm -rf /var/www/html/.git
              git clone https://github.com/hikaru-sugita/wordpress-deploy-test.git /var/www/html
            fi

            # 動的データ（例: uploads, cache）を保護
            sudo rm -rf /var/www/html/wp-content/cache/*

            # 権限設定
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            # Apache再起動
            sudo systemctl restart apache2
